/* Generated by re2c 1.0.1 on Sat Aug 25 08:25:52 2018 */
#line 1 "src/I386ASM/Parser.re"
#include "I386ASM/Parser.hpp"

#include "I386ASM/Instruction/Halt.hpp"
#include "I386ASM/Instruction/Jump.hpp"
#include "I386ASM/Instruction/Move.hpp"

#define YYMAXFILL 11

#define SIZE 500

Parser::Parser(Environment &env):
    Object(env),
    buffer((char*) env.getAllocator().allocate(SIZE + YYMAXFILL).buf),
    linesBuffer((int*) env.getAllocator().allocate((SIZE + YYMAXFILL) * sizeof(int)).buf),
    columnsBuffer((int*) env.getAllocator().allocate((SIZE + YYMAXFILL) * sizeof(int)).buf),
    currentLine(1),
    currentColumn(1) {
}

Parser::~Parser() {
    env().getAllocator().free(buffer);
    env().getAllocator().free(linesBuffer);
    env().getAllocator().free(columnsBuffer);
}

bool Parser::freeBuffer(size_t need) {
    const size_t free = token - buffer;
    const size_t filled = limit - token;
    if (free < need) {
        return false;
    }
    for (int i = 0; i < filled; i++) {
        buffer[i] = buffer[i + free];
        linesBuffer[i] = linesBuffer[i + free];
        columnsBuffer[i] = columnsBuffer[i + free];
    }
    limit -= free;
    current -= free;
    token -= free;
    marker -= free;
    ctxmarker -= free;
    return true;
}

bool Parser::fillBuffer(size_t need, IStream & input)
{
    if (input.empty() || !freeBuffer(need)) {
        return false;
    }
    char current;
    while (!input.empty() && (limit < buffer + SIZE)) {
        input >> current;
        linesBuffer[limit - buffer] = currentLine;
        columnsBuffer[limit - buffer] = currentColumn++;
        *limit++ = current;
        if (current == '\n') {
            currentLine++;
            currentColumn = 1;
        }
    }
    if (limit < buffer + SIZE) {
        // clear lookahead after end of stream
        char * maxfill = limit + YYMAXFILL;
        while (limit < maxfill) {
            linesBuffer[limit - buffer] = 0;
            columnsBuffer[limit - buffer] = 0;
            *limit++ = (char) 0;
        }
    }
    return true;
};

// public
ASMInstructionList & Parser::parse(IStream & input, int line, int column) {
    OStream & log = env().getStdO();
    ASMInstructionList & list = env().create<ASMInstructionList>();
    
    // reset parsing buffer
    token = current = marker = ctxmarker = limit = buffer + SIZE;
    currentLine = line;
    currentColumn = column;
    
    char *o1, *o2, *o3, *o4, *o5, *o6, *o7, *o8;
    
    log << "parse input\n";
    
    for (;;) {
        token = current;
char *yyt1;char *yyt10;char *yyt11;char *yyt12;char *yyt13;char *yyt2;char *yyt3;char *yyt4;char *yyt5;char *yyt6;char *yyt7;char *yyt8;char *yyt9;

#line 94 "src/I386ASM/Parser.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((limit - current) < 11) if (!fillBuffer(11, input)) break;
	yych = *current;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case ' ':	goto yy6;
	case '#':	goto yy9;
	case '/':	goto yy10;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = current;
		goto yy11;
	case ';':	goto yy12;
	case 'A':
	case 'a':
		yyt1 = current;
		goto yy14;
	case 'H':
	case 'h':
		yyt1 = current;
		goto yy15;
	case 'I':
	case 'i':
		yyt1 = current;
		goto yy16;
	case 'J':
	case 'j':
		yyt1 = current;
		goto yy17;
	case 'M':
	case 'm':
		yyt1 = current;
		goto yy18;
	case 'S':
	case 's':
		yyt1 = current;
		goto yy19;
	default:	goto yy4;
	}
yy2:
	++current;
#line 127 "src/I386ASM/Parser.re"
	{ break; }
#line 191 "src/I386ASM/Parser.cpp"
yy4:
	++current;
yy5:
#line 168 "src/I386ASM/Parser.re"
	{ log << "error: " << *token << " line: " << linesBuffer[token-buffer] << " column: "  << columnsBuffer[token-buffer] << '\n'; break; }
#line 197 "src/I386ASM/Parser.cpp"
yy6:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 128 "src/I386ASM/Parser.re"
	{ continue; }
#line 211 "src/I386ASM/Parser.cpp"
yy9:
	yych = *++current;
	yyt1 = current;
	goto yy21;
yy10:
	yych = *++current;
	switch (yych) {
	case '*':	goto yy24;
	case '/':	goto yy9;
	default:	goto yy5;
	}
yy11:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	default:	goto yy5;
	}
yy12:
	++current;
#line 129 "src/I386ASM/Parser.re"
	{ continue; }
#line 300 "src/I386ASM/Parser.cpp"
yy14:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'D':
	case 'd':	goto yy32;
	default:	goto yy5;
	}
yy15:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'L':
	case 'l':	goto yy33;
	default:	goto yy5;
	}
yy16:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'M':
	case 'm':	goto yy34;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'M':
	case 'm':	goto yy35;
	default:	goto yy5;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'O':
	case 'o':	goto yy36;
	case 'U':
	case 'u':	goto yy37;
	default:	goto yy5;
	}
yy19:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy29;
	case 'U':
	case 'u':	goto yy38;
	default:	goto yy5;
	}
yy20:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
yy21:
	switch (yych) {
	case '\n':	goto yy22;
	default:	goto yy20;
	}
yy22:
	++current;
	o1 = yyt1;
	o2 = current - 1;
#line 130 "src/I386ASM/Parser.re"
	{
                    log << "linec: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue;
                  }
#line 756 "src/I386ASM/Parser.cpp"
yy24:
	yych = *++current;
	yyt1 = current;
	goto yy40;
yy25:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy25;
	case ':':	goto yy30;
	default:	goto yy27;
	}
yy27:
	current = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy31;
	case 2: 	goto yy56;
	case 3: 	goto yy71;
	case 4: 	goto yy95;
	case 5: 
		yyt2 = yyt10;
		goto yy95;
	case 6: 	goto yy163;
	case 7: 
		yyt3 = yyt11;
		goto yy163;
	case 8: 	goto yy222;
	default:
		yyt3 = yyt12;
		goto yy222;
	}
yy28:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy29:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
		yyt6 = yyt7 = current;
		goto yy25;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy28;
	case ':':
		yyt6 = yyt7 = current;
		goto yy30;
	default:	goto yy27;
	}
yy30:
	yyaccept = 1;
	yych = *(marker = ++current);
	switch (yych) {
	case '=':	goto yy42;
	default:	goto yy31;
	}
yy31:
	o1 = yyt1;
	o2 = yyt6;
#line 137 "src/I386ASM/Parser.re"
	{
                    log << "label: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue; }
#line 884 "src/I386ASM/Parser.cpp"
yy32:
	yych = *++current;
	switch (yych) {
	case 'D':
	case 'd':	goto yy44;
	default:	goto yy29;
	}
yy33:
	yych = *++current;
	switch (yych) {
	case 'T':
	case 't':	goto yy45;
	default:	goto yy29;
	}
yy34:
	yych = *++current;
	switch (yych) {
	case 'U':
	case 'u':	goto yy37;
	default:	goto yy29;
	}
yy35:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy45;
	default:	goto yy29;
	}
yy36:
	yych = *++current;
	switch (yych) {
	case 'V':
	case 'v':	goto yy44;
	default:	goto yy29;
	}
yy37:
	yych = *++current;
	switch (yych) {
	case 'L':
	case 'l':	goto yy44;
	default:	goto yy29;
	}
yy38:
	yych = *++current;
	switch (yych) {
	case 'B':
	case 'b':	goto yy44;
	default:	goto yy29;
	}
yy39:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
yy40:
	switch (yych) {
	case '*':	goto yy41;
	default:	goto yy39;
	}
yy41:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '/':	goto yy46;
	default:	goto yy39;
	}
yy42:
	++current;
	if ((limit - current) < 4) if (!fillBuffer(4, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy42;
	case '-':
		yyt2 = current;
		goto yy48;
	case '0':
		yyt2 = current;
		goto yy49;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = current;
		goto yy50;
	default:	goto yy27;
	}
yy44:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = yyt5 = yyt6 = yyt7 = yyt8 = current;
		goto yy52;
	case '\n':
		yyt2 = yyt3 = yyt5 = yyt6 = yyt7 = yyt8 = current;
		goto yy54;
	case '#':
	case ';':
		yyt2 = yyt3 = current;
		goto yy57;
	case '%':
		yyt5 = yyt8 = yyt9 = current;
		goto yy58;
	case '(':
		yyt5 = yyt8 = yyt9 = current;
		goto yy59;
	case '-':
		yyt5 = yyt8 = yyt9 = current;
		goto yy61;
	case '/':
		yyt2 = yyt3 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = yyt8 = yyt9 = current;
		goto yy63;
	case ':':
		yyt6 = yyt7 = current;
		goto yy30;
	case 'B':
	case 'L':
	case 'W':
	case 'b':
	case 'l':
	case 'w':
		yyt5 = yyt9 = current;
		goto yy65;
	default:	goto yy27;
	}
yy45:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = yyt5 = yyt6 = yyt7 = yyt8 = current;
		goto yy52;
	case '\n':
		yyt2 = yyt3 = yyt5 = yyt6 = yyt7 = yyt8 = current;
		goto yy54;
	case '#':
	case ';':
		yyt2 = yyt3 = current;
		goto yy57;
	case '%':
		yyt5 = yyt8 = yyt9 = current;
		goto yy58;
	case '(':
		yyt5 = yyt8 = yyt9 = current;
		goto yy59;
	case '-':
		yyt5 = yyt8 = yyt9 = current;
		goto yy61;
	case '/':
		yyt2 = yyt3 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = yyt8 = yyt9 = current;
		goto yy63;
	case ':':
		yyt6 = yyt7 = current;
		goto yy30;
	default:	goto yy27;
	}
yy46:
	++current;
	o1 = yyt1;
	o2 = current - 2;
#line 133 "src/I386ASM/Parser.re"
	{
                    log << "mlcom: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue;
                  }
#line 1180 "src/I386ASM/Parser.cpp"
yy48:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy66;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy50;
	default:	goto yy27;
	}
yy49:
	yych = *++current;
	switch (yych) {
	case 'B':
	case 'b':	goto yy76;
	case 'X':
	case 'x':	goto yy77;
	default:	goto yy75;
	}
yy50:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy73;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy50;
	default:	goto yy27;
	}
yy52:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy52;
	case '\n':
		yyt2 = current;
		goto yy54;
	case '#':
	case ';':
		yyt2 = current;
		goto yy57;
	case '%':
		yyt9 = current;
		goto yy58;
	case '(':
		yyt9 = current;
		goto yy59;
	case '-':
		yyt9 = current;
		goto yy61;
	case '/':
		yyt2 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt9 = current;
		goto yy78;
	case ':':	goto yy30;
	default:	goto yy27;
	}
yy54:
	yyaccept = 2;
	marker = ++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt4 = yyt2;
		goto yy52;
	case '\n':
		yyt2 = current;
		goto yy54;
	case '#':
	case ';':
		yyt2 = current;
		goto yy57;
	case '%':
		yyt4 = yyt2;
		yyt9 = current;
		goto yy58;
	case '(':
		yyt4 = yyt2;
		yyt9 = current;
		goto yy59;
	case '-':
		yyt4 = yyt2;
		yyt9 = current;
		goto yy61;
	case '/':
		yyt4 = yyt2;
		yyt2 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt4 = yyt2;
		yyt9 = current;
		goto yy78;
	case ':':	goto yy30;
	default:
		yyt4 = yyt2;
		goto yy56;
	}
yy56:
	o1 = yyt1;
	o2 = yyt3;
	current = yyt4;
#line 142 "src/I386ASM/Parser.re"
	{
                    log << "inst0: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 1444 "src/I386ASM/Parser.cpp"
yy57:
	++current;
	yyt4 = yyt2;
	goto yy56;
yy58:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy80;
	case 'B':
	case 'b':	goto yy81;
	case 'C':
	case 'c':	goto yy82;
	case 'D':
	case 'd':	goto yy83;
	case 'E':
	case 'e':	goto yy84;
	case 'I':
	case 'i':	goto yy85;
	case 'S':
	case 's':	goto yy86;
	default:	goto yy27;
	}
yy59:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy59;
	case '%':	goto yy87;
	default:	goto yy27;
	}
yy61:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy88;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy89;
	default:	goto yy27;
	}
yy62:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy57;
	default:	goto yy27;
	}
yy63:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy64:
	switch (yych) {
	case '\t':
	case ' ':
		yyt6 = yyt7 = yyt10 = current;
		goto yy91;
	case '\n':
		yyt6 = yyt7 = yyt10 = yyt11 = current;
		goto yy93;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy63;
	case ':':
		yyt6 = yyt7 = current;
		goto yy30;
	default:	goto yy27;
	}
yy65:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = yyt6 = yyt7 = yyt8 = yyt10 = current;
		goto yy100;
	case '\n':
		yyt2 = yyt3 = yyt6 = yyt7 = yyt8 = yyt10 = current;
		goto yy102;
	case '#':
	case ';':
		yyt2 = yyt3 = current;
		goto yy57;
	case '%':
		yyt5 = yyt8 = yyt9 = current;
		goto yy58;
	case '(':
		yyt5 = yyt8 = yyt9 = current;
		goto yy59;
	case '-':
		yyt5 = yyt8 = yyt9 = current;
		goto yy61;
	case '/':
		yyt2 = yyt3 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = yyt8 = yyt9 = current;
		goto yy63;
	default:	goto yy64;
	}
yy66:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy74;
	case 'B':
	case 'b':	goto yy76;
	case 'X':
	case 'x':	goto yy77;
	default:	goto yy27;
	}
yy67:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy67;
	case '\n':
		yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt4 = current;
		goto yy72;
	case '/':
		yyt4 = current;
		goto yy73;
	default:	goto yy27;
	}
yy69:
	yyaccept = 3;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt4;
		goto yy67;
	case '\n':
		yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt4 = current;
		goto yy72;
	case '/':
		yyt5 = yyt4;
		yyt4 = current;
		goto yy73;
	default:
		yyt5 = yyt4;
		goto yy71;
	}
yy71:
	o1 = yyt1;
	o2 = yyt7;
	o3 = yyt2;
	o4 = yyt3;
	current = yyt5;
#line 139 "src/I386ASM/Parser.re"
	{
                    log << "defin: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << " as "; for (char * cur = o3; cur < o4; cur++) { log << *cur; };log << '\n'; continue;
                  }
#line 1757 "src/I386ASM/Parser.cpp"
yy72:
	++current;
	yyt5 = yyt4;
	goto yy71;
yy73:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy72;
	default:	goto yy27;
	}
yy74:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy75:
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy73;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy74;
	default:	goto yy27;
	}
yy76:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy104;
	default:	goto yy27;
	}
yy77:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	default:	goto yy27;
	}
yy78:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10 = current;
		goto yy108;
	case '\n':
		yyt2 = yyt3 = yyt10 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy78;
	default:	goto yy27;
	}
yy80:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy81:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy82:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy83:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy84:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy113;
	case 'B':
	case 'b':	goto yy114;
	case 'D':
	case 'd':	goto yy115;
	case 'I':
	case 'i':	goto yy85;
	case 'S':
	case 's':	goto yy116;
	default:	goto yy27;
	}
yy85:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy112;
	default:	goto yy27;
	}
yy86:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy112;
	default:	goto yy27;
	}
yy87:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy117;
	case 'B':
	case 'b':	goto yy118;
	case 'C':
	case 'c':	goto yy119;
	case 'D':
	case 'd':	goto yy120;
	case 'E':
	case 'e':	goto yy121;
	case 'I':
	case 'i':	goto yy122;
	case 'S':
	case 's':	goto yy123;
	default:	goto yy27;
	}
yy88:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy124;
	case 'B':
	case 'b':	goto yy126;
	case 'X':
	case 'x':	goto yy127;
	default:	goto yy27;
	}
yy89:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10 = current;
		goto yy108;
	case '\n':
		yyt2 = yyt3 = yyt10 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy89;
	default:	goto yy27;
	}
yy91:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy91;
	case '\n':
		yyt11 = current;
		goto yy93;
	case '#':
	case ';':
		yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':	goto yy97;
	case '/':
		yyt11 = current;
		goto yy99;
	case ':':	goto yy30;
	default:	goto yy27;
	}
yy93:
	yyaccept = 4;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10;
		yyt3 = yyt11;
		goto yy91;
	case '\n':
		yyt11 = current;
		goto yy93;
	case '#':
	case ';':
		yyt11 = current;
		goto yy96;
	case '(':
		yyt2 = yyt10;
		yyt3 = yyt11;
		goto yy59;
	case ',':
		yyt2 = yyt10;
		yyt3 = yyt11;
		goto yy97;
	case '/':
		yyt2 = yyt10;
		yyt3 = yyt11;
		yyt11 = current;
		goto yy99;
	case ':':	goto yy30;
	default:
		yyt2 = yyt10;
		yyt3 = yyt11;
		goto yy95;
	}
yy95:
	o1 = yyt1;
	o2 = yyt8;
	o3 = yyt9;
	o4 = yyt2;
	current = yyt3;
#line 147 "src/I386ASM/Parser.re"
	{
                    log << "inst1: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 2151 "src/I386ASM/Parser.cpp"
yy96:
	++current;
	yyt2 = yyt10;
	yyt3 = yyt11;
	goto yy95;
yy97:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy97;
	case '%':
		yyt6 = current;
		goto yy128;
	case '(':
		yyt6 = current;
		goto yy129;
	case '-':
		yyt6 = current;
		goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = current;
		goto yy132;
	default:	goto yy27;
	}
yy99:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy96;
	default:	goto yy27;
	}
yy100:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy100;
	case '\n':
		yyt2 = current;
		goto yy102;
	case '#':
	case ';':
		yyt2 = current;
		goto yy57;
	case '%':
		yyt5 = yyt3;
		yyt9 = current;
		goto yy58;
	case '(':
		yyt5 = yyt3;
		yyt9 = current;
		goto yy59;
	case ',':	goto yy97;
	case '-':
		yyt5 = yyt3;
		yyt9 = current;
		goto yy61;
	case '/':
		yyt2 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt5 = yyt3;
		yyt9 = current;
		goto yy78;
	case ':':	goto yy30;
	default:	goto yy27;
	}
yy102:
	yyaccept = 2;
	marker = ++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt4 = yyt2;
		goto yy100;
	case '\n':
		yyt2 = current;
		goto yy102;
	case '#':
	case ';':
		yyt2 = current;
		goto yy57;
	case '%':
		yyt4 = yyt2;
		yyt5 = yyt3;
		yyt9 = current;
		goto yy58;
	case '(':
		yyt4 = yyt2;
		yyt5 = yyt3;
		yyt9 = current;
		goto yy59;
	case ',':
		yyt4 = yyt2;
		goto yy97;
	case '-':
		yyt4 = yyt2;
		yyt5 = yyt3;
		yyt9 = current;
		goto yy61;
	case '/':
		yyt4 = yyt2;
		yyt2 = current;
		goto yy62;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt4 = yyt2;
		yyt5 = yyt3;
		yyt9 = current;
		goto yy78;
	case ':':	goto yy30;
	default:
		yyt4 = yyt2;
		goto yy56;
	}
yy104:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy73;
	case '0':
	case '1':	goto yy104;
	default:	goto yy27;
	}
yy106:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = yyt4 = current;
		goto yy69;
	case '#':
	case ';':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy73;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	default:	goto yy27;
	}
yy108:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy108;
	case '\n':
		yyt3 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt2;
		yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':	goto yy97;
	case '/':
		yyt10 = yyt2;
		yyt11 = current;
		goto yy99;
	default:	goto yy27;
	}
yy110:
	yyaccept = 4;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy108;
	case '\n':
		yyt3 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt2;
		yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':	goto yy97;
	case '/':
		yyt10 = yyt2;
		yyt11 = current;
		goto yy99;
	default:	goto yy95;
	}
yy112:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt10 = current;
		goto yy134;
	case '\n':
		yyt3 = yyt10 = current;
		goto yy136;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	default:	goto yy27;
	}
yy113:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy114:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy115:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy112;
	default:	goto yy27;
	}
yy116:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt10 = current;
		goto yy134;
	case '\n':
		yyt3 = yyt10 = current;
		goto yy136;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy112;
	default:	goto yy27;
	}
yy117:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy118:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy119:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy120:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy121:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy140;
	case 'B':
	case 'b':	goto yy141;
	case 'D':
	case 'd':	goto yy142;
	case 'I':
	case 'i':	goto yy122;
	case 'S':
	case 's':	goto yy143;
	default:	goto yy27;
	}
yy122:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy138;
	default:	goto yy27;
	}
yy123:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy138;
	default:	goto yy27;
	}
yy124:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10 = current;
		goto yy108;
	case '\n':
		yyt2 = yyt3 = yyt10 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy124;
	default:	goto yy27;
	}
yy126:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy144;
	default:	goto yy27;
	}
yy127:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy146;
	default:	goto yy27;
	}
yy128:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy148;
	case 'B':
	case 'b':	goto yy149;
	case 'C':
	case 'c':	goto yy150;
	case 'D':
	case 'd':	goto yy151;
	case 'E':
	case 'e':	goto yy152;
	case 'I':
	case 'i':	goto yy153;
	case 'S':
	case 's':	goto yy154;
	default:	goto yy27;
	}
yy129:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy129;
	case '%':	goto yy155;
	default:	goto yy27;
	}
yy131:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy156;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy157;
	default:	goto yy27;
	}
yy132:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy159;
	case '\n':
		yyt7 = yyt11 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy132;
	default:	goto yy27;
	}
yy134:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy134;
	case '\n':
		yyt3 = current;
		goto yy136;
	case '#':
	case ';':
		yyt11 = current;
		goto yy96;
	case ',':	goto yy97;
	case '/':
		yyt11 = current;
		goto yy99;
	default:	goto yy27;
	}
yy136:
	yyaccept = 5;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy134;
	case '\n':
		yyt3 = current;
		goto yy136;
	case '#':
	case ';':
		yyt11 = current;
		goto yy96;
	case ',':	goto yy97;
	case '/':
		yyt11 = current;
		goto yy99;
	default:
		yyt2 = yyt10;
		goto yy95;
	}
yy138:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy139:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy138;
	case ')':	goto yy112;
	case ',':	goto yy168;
	default:	goto yy27;
	}
yy140:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy141:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy142:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy138;
	default:	goto yy27;
	}
yy143:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy138;
	default:	goto yy139;
	}
yy144:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10 = current;
		goto yy108;
	case '\n':
		yyt2 = yyt3 = yyt10 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':	goto yy144;
	default:	goto yy27;
	}
yy146:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt10 = current;
		goto yy108;
	case '\n':
		yyt2 = yyt3 = yyt10 = current;
		goto yy110;
	case '#':
	case ';':
		yyt10 = yyt11 = current;
		goto yy96;
	case '(':	goto yy59;
	case ',':
		yyt10 = current;
		goto yy97;
	case '/':
		yyt10 = yyt11 = current;
		goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy146;
	default:	goto yy27;
	}
yy148:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy149:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy150:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy151:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy152:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy171;
	case 'B':
	case 'b':	goto yy172;
	case 'D':
	case 'd':	goto yy173;
	case 'I':
	case 'i':	goto yy153;
	case 'S':
	case 's':	goto yy174;
	default:	goto yy27;
	}
yy153:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy170;
	default:	goto yy27;
	}
yy154:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy170;
	default:	goto yy27;
	}
yy155:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy175;
	case 'B':
	case 'b':	goto yy176;
	case 'C':
	case 'c':	goto yy177;
	case 'D':
	case 'd':	goto yy178;
	case 'E':
	case 'e':	goto yy179;
	case 'I':
	case 'i':	goto yy180;
	case 'S':
	case 's':	goto yy181;
	default:	goto yy27;
	}
yy156:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy182;
	case 'B':
	case 'b':	goto yy184;
	case 'X':
	case 'x':	goto yy185;
	default:	goto yy27;
	}
yy157:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy159;
	case '\n':
		yyt7 = yyt11 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy157;
	default:	goto yy27;
	}
yy159:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy159;
	case '\n':
		yyt7 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':	goto yy165;
	case '/':
		yyt7 = current;
		goto yy167;
	default:	goto yy27;
	}
yy161:
	yyaccept = 6;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt7;
		yyt3 = yyt11;
		goto yy159;
	case '\n':
		yyt7 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = current;
		goto yy164;
	case '(':
		yyt2 = yyt7;
		yyt3 = yyt11;
		goto yy129;
	case ',':
		yyt2 = yyt7;
		yyt3 = yyt11;
		goto yy165;
	case '/':
		yyt2 = yyt7;
		yyt3 = yyt11;
		yyt7 = current;
		goto yy167;
	default:
		yyt2 = yyt7;
		yyt3 = yyt11;
		goto yy163;
	}
yy163:
	o1 = yyt1;
	o2 = yyt5;
	o3 = yyt9;
	o4 = yyt10;
	o5 = yyt6;
	o6 = yyt3;
	current = yyt2;
#line 153 "src/I386ASM/Parser.re"
	{
                    log << "inst2: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 3326 "src/I386ASM/Parser.cpp"
yy164:
	++current;
	yyt2 = yyt7;
	yyt3 = yyt11;
	goto yy163;
yy165:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy165;
	case '%':
		yyt7 = current;
		goto yy186;
	case '(':
		yyt7 = current;
		goto yy187;
	case '-':
		yyt7 = current;
		goto yy189;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt7 = current;
		goto yy190;
	default:	goto yy27;
	}
yy167:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy164;
	default:	goto yy27;
	}
yy168:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy168;
	case '%':	goto yy192;
	default:	goto yy27;
	}
yy170:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy193;
	case '\n':
		yyt2 = yyt11 = current;
		goto yy195;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	default:	goto yy27;
	}
yy171:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy172:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy173:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy170;
	default:	goto yy27;
	}
yy174:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy193;
	case '\n':
		yyt2 = yyt11 = current;
		goto yy195;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy170;
	default:	goto yy27;
	}
yy175:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy176:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy177:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy178:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy179:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy199;
	case 'B':
	case 'b':	goto yy200;
	case 'D':
	case 'd':	goto yy201;
	case 'I':
	case 'i':	goto yy180;
	case 'S':
	case 's':	goto yy202;
	default:	goto yy27;
	}
yy180:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy197;
	default:	goto yy27;
	}
yy181:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy197;
	default:	goto yy27;
	}
yy182:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy159;
	case '\n':
		yyt7 = yyt11 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy182;
	default:	goto yy27;
	}
yy184:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy203;
	default:	goto yy27;
	}
yy185:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy205;
	default:	goto yy27;
	}
yy186:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy207;
	case 'B':
	case 'b':	goto yy208;
	case 'C':
	case 'c':	goto yy209;
	case 'D':
	case 'd':	goto yy210;
	case 'E':
	case 'e':	goto yy211;
	case 'I':
	case 'i':	goto yy212;
	case 'S':
	case 's':	goto yy213;
	default:	goto yy27;
	}
yy187:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy187;
	case '%':	goto yy214;
	default:	goto yy27;
	}
yy189:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy215;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy216;
	default:	goto yy27;
	}
yy190:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy218;
	case '\n':
		yyt12 = yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy190;
	default:	goto yy27;
	}
yy192:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy225;
	case 'B':
	case 'b':	goto yy226;
	case 'C':
	case 'c':	goto yy227;
	case 'D':
	case 'd':	goto yy228;
	case 'E':
	case 'e':	goto yy229;
	case 'I':
	case 'i':	goto yy230;
	case 'S':
	case 's':	goto yy231;
	default:	goto yy27;
	}
yy193:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy193;
	case '\n':
		yyt2 = current;
		goto yy195;
	case '#':
	case ';':
		yyt7 = current;
		goto yy164;
	case ',':	goto yy165;
	case '/':
		yyt7 = current;
		goto yy167;
	default:	goto yy27;
	}
yy195:
	yyaccept = 7;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy193;
	case '\n':
		yyt2 = current;
		goto yy195;
	case '#':
	case ';':
		yyt7 = current;
		goto yy164;
	case ',':	goto yy165;
	case '/':
		yyt7 = current;
		goto yy167;
	default:
		yyt3 = yyt11;
		goto yy163;
	}
yy197:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy198:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy197;
	case ')':	goto yy170;
	case ',':	goto yy232;
	default:	goto yy27;
	}
yy199:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy200:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy201:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy197;
	default:	goto yy27;
	}
yy202:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy197;
	default:	goto yy198;
	}
yy203:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy159;
	case '\n':
		yyt7 = yyt11 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case '0':
	case '1':	goto yy203;
	default:	goto yy27;
	}
yy205:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt11 = current;
		goto yy159;
	case '\n':
		yyt7 = yyt11 = current;
		goto yy161;
	case '#':
	case ';':
		yyt7 = yyt11 = current;
		goto yy164;
	case '(':	goto yy129;
	case ',':
		yyt11 = current;
		goto yy165;
	case '/':
		yyt7 = yyt11 = current;
		goto yy167;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy205;
	default:	goto yy27;
	}
yy207:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy208:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy209:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy210:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy211:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy235;
	case 'B':
	case 'b':	goto yy236;
	case 'D':
	case 'd':	goto yy237;
	case 'I':
	case 'i':	goto yy212;
	case 'S':
	case 's':	goto yy238;
	default:	goto yy27;
	}
yy212:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy234;
	default:	goto yy27;
	}
yy213:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy234;
	default:	goto yy27;
	}
yy214:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy239;
	case 'B':
	case 'b':	goto yy240;
	case 'C':
	case 'c':	goto yy241;
	case 'D':
	case 'd':	goto yy242;
	case 'E':
	case 'e':	goto yy243;
	case 'I':
	case 'i':	goto yy244;
	case 'S':
	case 's':	goto yy245;
	default:	goto yy27;
	}
yy215:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy246;
	case 'B':
	case 'b':	goto yy248;
	case 'X':
	case 'x':	goto yy249;
	default:	goto yy27;
	}
yy216:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy218;
	case '\n':
		yyt12 = yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy216;
	default:	goto yy27;
	}
yy218:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy218;
	case '\n':
		yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt13 = current;
		goto yy224;
	default:	goto yy27;
	}
yy220:
	yyaccept = 8;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt13;
		yyt3 = yyt12;
		goto yy218;
	case '\n':
		yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt13 = current;
		goto yy223;
	case '(':
		yyt2 = yyt13;
		yyt3 = yyt12;
		goto yy187;
	case '/':
		yyt2 = yyt13;
		yyt3 = yyt12;
		yyt13 = current;
		goto yy224;
	default:
		yyt2 = yyt13;
		yyt3 = yyt12;
		goto yy222;
	}
yy222:
	o1 = yyt1;
	o2 = yyt5;
	o3 = yyt9;
	o4 = yyt10;
	o5 = yyt6;
	o6 = yyt11;
	o7 = yyt7;
	o8 = yyt3;
	current = yyt2;
#line 160 "src/I386ASM/Parser.re"
	{
                    log << "inst3: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o7; cur < o8; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 4200 "src/I386ASM/Parser.cpp"
yy223:
	++current;
	yyt2 = yyt13;
	yyt3 = yyt12;
	goto yy222;
yy224:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy223;
	default:	goto yy27;
	}
yy225:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy226:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy227:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy228:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy229:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy252;
	case 'B':
	case 'b':	goto yy253;
	case 'D':
	case 'd':	goto yy254;
	case 'I':
	case 'i':	goto yy230;
	case 'S':
	case 's':	goto yy255;
	default:	goto yy27;
	}
yy230:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy250;
	default:	goto yy27;
	}
yy231:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy250;
	default:	goto yy27;
	}
yy232:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy232;
	case '%':	goto yy256;
	default:	goto yy27;
	}
yy234:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy257;
	case '\n':
		yyt2 = yyt12 = current;
		goto yy259;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	default:	goto yy27;
	}
yy235:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy236:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy237:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy234;
	default:	goto yy27;
	}
yy238:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy257;
	case '\n':
		yyt2 = yyt12 = current;
		goto yy259;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy234;
	default:	goto yy27;
	}
yy239:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy240:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy241:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy242:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy243:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy263;
	case 'B':
	case 'b':	goto yy264;
	case 'D':
	case 'd':	goto yy265;
	case 'I':
	case 'i':	goto yy244;
	case 'S':
	case 's':	goto yy266;
	default:	goto yy27;
	}
yy244:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy261;
	default:	goto yy27;
	}
yy245:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy261;
	default:	goto yy27;
	}
yy246:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy218;
	case '\n':
		yyt12 = yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy246;
	default:	goto yy27;
	}
yy248:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy267;
	default:	goto yy27;
	}
yy249:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy269;
	default:	goto yy27;
	}
yy250:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy251:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy250;
	case ')':	goto yy112;
	case ',':	goto yy271;
	default:	goto yy27;
	}
yy252:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy253:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy254:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy250;
	default:	goto yy27;
	}
yy255:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy250;
	default:	goto yy251;
	}
yy256:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy273;
	case 'B':
	case 'b':	goto yy274;
	case 'C':
	case 'c':	goto yy275;
	case 'D':
	case 'd':	goto yy276;
	case 'E':
	case 'e':	goto yy277;
	case 'I':
	case 'i':	goto yy278;
	case 'S':
	case 's':	goto yy279;
	default:	goto yy27;
	}
yy257:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy257;
	case '\n':
		yyt2 = current;
		goto yy259;
	case '#':
	case ';':
		yyt13 = current;
		goto yy223;
	case '/':
		yyt13 = current;
		goto yy224;
	default:	goto yy27;
	}
yy259:
	yyaccept = 9;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy257;
	case '\n':
		yyt2 = current;
		goto yy259;
	case '#':
	case ';':
		yyt13 = current;
		goto yy223;
	case '/':
		yyt13 = current;
		goto yy224;
	default:
		yyt3 = yyt12;
		goto yy222;
	}
yy261:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy262:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy261;
	case ')':	goto yy234;
	case ',':	goto yy280;
	default:	goto yy27;
	}
yy263:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy264:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy265:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy261;
	default:	goto yy27;
	}
yy266:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy261;
	default:	goto yy262;
	}
yy267:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy218;
	case '\n':
		yyt12 = yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case '0':
	case '1':	goto yy267;
	default:	goto yy27;
	}
yy269:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt12 = current;
		goto yy218;
	case '\n':
		yyt12 = yyt13 = current;
		goto yy220;
	case '#':
	case ';':
		yyt12 = yyt13 = current;
		goto yy223;
	case '(':	goto yy187;
	case '/':
		yyt12 = yyt13 = current;
		goto yy224;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy269;
	default:	goto yy27;
	}
yy271:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy271;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy282;
	default:	goto yy27;
	}
yy273:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy274:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy275:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy276:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy277:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy286;
	case 'B':
	case 'b':	goto yy287;
	case 'D':
	case 'd':	goto yy288;
	case 'I':
	case 'i':	goto yy278;
	case 'S':
	case 's':	goto yy289;
	default:	goto yy27;
	}
yy278:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy284;
	default:	goto yy27;
	}
yy279:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy284;
	default:	goto yy27;
	}
yy280:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy280;
	case '%':	goto yy290;
	default:	goto yy27;
	}
yy282:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy282;
	case ')':	goto yy112;
	default:	goto yy27;
	}
yy284:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy285:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy284;
	case ')':	goto yy170;
	case ',':	goto yy291;
	default:	goto yy27;
	}
yy286:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy287:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy288:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy284;
	default:	goto yy27;
	}
yy289:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy284;
	default:	goto yy285;
	}
yy290:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy293;
	case 'B':
	case 'b':	goto yy294;
	case 'C':
	case 'c':	goto yy295;
	case 'D':
	case 'd':	goto yy296;
	case 'E':
	case 'e':	goto yy297;
	case 'I':
	case 'i':	goto yy298;
	case 'S':
	case 's':	goto yy299;
	default:	goto yy27;
	}
yy291:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy291;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy300;
	default:	goto yy27;
	}
yy293:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy294:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy295:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy296:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy297:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy304;
	case 'B':
	case 'b':	goto yy305;
	case 'D':
	case 'd':	goto yy306;
	case 'I':
	case 'i':	goto yy298;
	case 'S':
	case 's':	goto yy307;
	default:	goto yy27;
	}
yy298:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy302;
	default:	goto yy27;
	}
yy299:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy302;
	default:	goto yy27;
	}
yy300:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy300;
	case ')':	goto yy170;
	default:	goto yy27;
	}
yy302:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy303:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy302;
	case ')':	goto yy234;
	case ',':	goto yy308;
	default:	goto yy27;
	}
yy304:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy305:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy306:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy302;
	default:	goto yy27;
	}
yy307:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy302;
	default:	goto yy303;
	}
yy308:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy308;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy310;
	default:	goto yy27;
	}
yy310:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy310;
	case ')':	goto yy234;
	default:	goto yy27;
	}
}
#line 169 "src/I386ASM/Parser.re"

    }
    
    // TODO: fill list via re2c
    list.addInstruction(env().create<Move>());
    list.addInstruction(env().create<Halt>());
    list.addInstruction(env().create<Jump>());
    log << "parse input done\n";
    return list;
}
