/* Generated by re2c 1.0.1 on Fri Aug 24 08:27:59 2018 */
#line 1 "src/I386ASM/Parser.re"
#include "I386ASM/Parser.hpp"

#define YYMAXFILL 11

#define SIZE 500

Parser::Parser(Environment &env):
    Object(env),
    buffer((char*) env.getAllocator().allocate(SIZE + YYMAXFILL).buf) {
}

Parser:: ~Parser() {
    env().getAllocator().free(buffer);
}

bool Parser::freeBuffer(size_t need) {
    const size_t free = token - buffer;
    if (free < need) {
        return false;
    }
    for (char *src = token, *dest = buffer; src < limit; src++, dest++) {
        *dest = *src;
    }
    limit -= free;
    current -= free;
    token -= free;
    marker -= free;
    ctxmarker -= free;
    return true;
}

bool Parser::fillBuffer(size_t need, IStream & input)
{
    if (input.empty() || !freeBuffer(need)) {
        return false;
    }
    while (!input.empty() && (limit < buffer + SIZE)) {
        input >> *limit++;
    }
    if (limit < buffer + SIZE) {
        // clear lookahead after end of stream
        char * maxfill = limit + YYMAXFILL;
        while (limit < maxfill) {
            *limit++ = (char) 0;
        }
    }
    return true;
};

// public
ASMInstructionList & Parser::parse(IStream & input) {
    OStream & log = env().getStdO();
    ASMInstructionList & list = env().create<ASMInstructionList>();
    
    // reset parsing buffer
    token = current = marker = ctxmarker = limit = buffer + SIZE;
    
    char *o1, *o2, *o3, *o4, *o5, *o6, *o7, *o8;
    
    log << "parse input\n";
    
    for (;;) {
        token = current;
char *yyt1;char *yyt10;char *yyt11;char *yyt12;char *yyt13;char *yyt14;char *yyt2;char *yyt3;char *yyt4;char *yyt5;char *yyt6;char *yyt7;char *yyt8;char *yyt9;

#line 69 "src/I386ASM/Parser.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((limit - current) < 11) if (!fillBuffer(11, input)) break;
	yych = *current;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case ' ':	goto yy6;
	case '#':	goto yy9;
	case '/':	goto yy10;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = current;
		goto yy11;
	case 'A':
	case 'a':
		yyt1 = current;
		goto yy12;
	case 'H':
	case 'h':
		yyt1 = current;
		goto yy13;
	case 'I':
	case 'i':
		yyt1 = current;
		goto yy14;
	case 'J':
	case 'j':
		yyt1 = current;
		goto yy15;
	case 'M':
	case 'm':
		yyt1 = current;
		goto yy16;
	case 'S':
	case 's':
		yyt1 = current;
		goto yy17;
	default:	goto yy4;
	}
yy2:
	++current;
#line 102 "src/I386ASM/Parser.re"
	{ break; }
#line 165 "src/I386ASM/Parser.cpp"
yy4:
	++current;
yy5:
#line 171 "src/I386ASM/Parser.re"
	{ log << "error: " << *token << '\n'; break; }
#line 171 "src/I386ASM/Parser.cpp"
yy6:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
#line 103 "src/I386ASM/Parser.re"
	{ continue; }
#line 185 "src/I386ASM/Parser.cpp"
yy9:
	yych = *++current;
	yyt1 = current;
	goto yy19;
yy10:
	yych = *++current;
	switch (yych) {
	case '*':	goto yy22;
	case '/':	goto yy9;
	default:	goto yy5;
	}
yy11:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	default:	goto yy5;
	}
yy12:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'D':
	case 'd':	goto yy30;
	default:	goto yy5;
	}
yy13:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'L':
	case 'l':	goto yy31;
	default:	goto yy5;
	}
yy14:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'M':
	case 'm':	goto yy32;
	default:	goto yy5;
	}
yy15:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'M':
	case 'm':	goto yy33;
	default:	goto yy5;
	}
yy16:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'O':
	case 'o':	goto yy34;
	case 'U':
	case 'u':	goto yy35;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(marker = ++current);
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy27;
	case 'U':
	case 'u':	goto yy36;
	default:	goto yy5;
	}
yy18:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
yy19:
	switch (yych) {
	case '\n':	goto yy20;
	default:	goto yy18;
	}
yy20:
	++current;
	o1 = yyt1;
	o2 = current - 1;
#line 104 "src/I386ASM/Parser.re"
	{
                    log << "linec: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue;
                  }
#line 725 "src/I386ASM/Parser.cpp"
yy22:
	yych = *++current;
	yyt1 = current;
	goto yy38;
yy23:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy23;
	case ':':	goto yy28;
	default:	goto yy25;
	}
yy25:
	current = marker;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy29;
	case 2: 	goto yy54;
	case 3: 	goto yy71;
	case 4: 	goto yy97;
	case 5: 
		yyt2 = yyt14;
		goto yy97;
	case 6: 	goto yy167;
	case 7: 
		yyt5 = yyt12;
		goto yy167;
	case 8: 	goto yy228;
	default:
		yyt8 = yyt13;
		goto yy228;
	}
yy26:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy27:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':
		yyt5 = yyt8 = yyt9 = current;
		goto yy23;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy26;
	case ':':
		yyt5 = yyt8 = yyt9 = current;
		goto yy28;
	default:	goto yy25;
	}
yy28:
	yyaccept = 1;
	yych = *(marker = ++current);
	switch (yych) {
	case '=':	goto yy40;
	default:	goto yy29;
	}
yy29:
	o1 = yyt1;
	o2 = yyt5;
#line 111 "src/I386ASM/Parser.re"
	{
                    log << "label: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue; }
#line 853 "src/I386ASM/Parser.cpp"
yy30:
	yych = *++current;
	switch (yych) {
	case 'D':
	case 'd':	goto yy42;
	default:	goto yy27;
	}
yy31:
	yych = *++current;
	switch (yych) {
	case 'T':
	case 't':	goto yy43;
	default:	goto yy27;
	}
yy32:
	yych = *++current;
	switch (yych) {
	case 'U':
	case 'u':	goto yy35;
	default:	goto yy27;
	}
yy33:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy43;
	default:	goto yy27;
	}
yy34:
	yych = *++current;
	switch (yych) {
	case 'V':
	case 'v':	goto yy42;
	default:	goto yy27;
	}
yy35:
	yych = *++current;
	switch (yych) {
	case 'L':
	case 'l':	goto yy42;
	default:	goto yy27;
	}
yy36:
	yych = *++current;
	switch (yych) {
	case 'B':
	case 'b':	goto yy42;
	default:	goto yy27;
	}
yy37:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
yy38:
	switch (yych) {
	case '*':	goto yy39;
	default:	goto yy37;
	}
yy39:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '/':	goto yy44;
	default:	goto yy37;
	}
yy40:
	++current;
	if ((limit - current) < 4) if (!fillBuffer(4, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy40;
	case '-':
		yyt2 = current;
		goto yy46;
	case '0':
		yyt2 = current;
		goto yy47;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt2 = current;
		goto yy48;
	default:	goto yy25;
	}
yy42:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt3 = yyt4 = yyt5 = yyt6 = yyt7 = yyt8 = yyt9 = yyt10 = current;
		goto yy50;
	case '\n':
		yyt2 = yyt3 = yyt4 = yyt5 = yyt6 = yyt7 = yyt8 = yyt9 = yyt10 = current;
		goto yy52;
	case '#':
		yyt2 = yyt3 = current;
		goto yy55;
	case '%':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case '-':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt2 = yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy62;
	case ':':
		yyt5 = yyt8 = yyt9 = current;
		goto yy28;
	case ';':
		yyt10 = current;
		goto yy64;
	case 'B':
	case 'L':
	case 'W':
	case 'b':
	case 'l':
	case 'w':
		yyt3 = yyt6 = yyt7 = yyt11 = yyt13 = current;
		goto yy65;
	default:	goto yy25;
	}
yy43:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt3 = yyt4 = yyt5 = yyt6 = yyt7 = yyt8 = yyt9 = yyt10 = current;
		goto yy50;
	case '\n':
		yyt2 = yyt3 = yyt4 = yyt5 = yyt6 = yyt7 = yyt8 = yyt9 = yyt10 = current;
		goto yy52;
	case '#':
		yyt2 = yyt3 = current;
		goto yy55;
	case '%':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case '-':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt2 = yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy62;
	case ':':
		yyt5 = yyt8 = yyt9 = current;
		goto yy28;
	case ';':
		yyt10 = current;
		goto yy64;
	default:	goto yy25;
	}
yy44:
	++current;
	o1 = yyt1;
	o2 = current - 2;
#line 107 "src/I386ASM/Parser.re"
	{
                    log << "mlcom: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << '\n'; continue;
                  }
#line 1153 "src/I386ASM/Parser.cpp"
yy46:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy66;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	default:	goto yy25;
	}
yy47:
	yych = *++current;
	switch (yych) {
	case 'B':
	case 'b':	goto yy78;
	case 'X':
	case 'x':	goto yy79;
	default:	goto yy76;
	}
yy48:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = current;
		goto yy69;
	case '#':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy74;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy48;
	case ';':
		yyt3 = current;
		goto yy77;
	default:	goto yy25;
	}
yy50:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy50;
	case '\n':	goto yy52;
	case '#':
		yyt3 = current;
		goto yy55;
	case '%':
		yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case '-':
		yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt11 = yyt12 = yyt13 = current;
		goto yy80;
	case ':':	goto yy28;
	case ';':	goto yy64;
	default:	goto yy25;
	}
yy52:
	yyaccept = 2;
	marker = ++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy50;
	case '\n':	goto yy52;
	case '#':
		yyt3 = current;
		goto yy55;
	case '%':
		yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case '-':
		yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt11 = yyt12 = yyt13 = current;
		goto yy80;
	case ':':	goto yy28;
	case ';':	goto yy64;
	default:	goto yy54;
	}
yy54:
	o1 = yyt1;
	o2 = yyt10;
#line 119 "src/I386ASM/Parser.re"
	{
                    log << "inst0: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 1405 "src/I386ASM/Parser.cpp"
yy55:
	++current;
	o1 = yyt1;
	o2 = yyt2;
	current = yyt3;
#line 124 "src/I386ASM/Parser.re"
	{
                    log << "inst0: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 1417 "src/I386ASM/Parser.cpp"
yy57:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy82;
	case 'B':
	case 'b':	goto yy83;
	case 'C':
	case 'c':	goto yy84;
	case 'D':
	case 'd':	goto yy85;
	case 'E':
	case 'e':	goto yy86;
	case 'I':
	case 'i':	goto yy87;
	case 'S':
	case 's':	goto yy88;
	default:	goto yy25;
	}
yy58:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy58;
	case '%':	goto yy89;
	default:	goto yy25;
	}
yy60:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy90;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	default:	goto yy25;
	}
yy61:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy55;
	default:	goto yy25;
	}
yy62:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy63:
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt9 = yyt14 = current;
		goto yy93;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt9 = yyt14 = current;
		goto yy95;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy62;
	case ':':
		yyt5 = yyt8 = yyt9 = current;
		goto yy28;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy64:
	++current;
	goto yy54;
yy65:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt4 = yyt5 = yyt8 = yyt9 = yyt10 = yyt14 = current;
		goto yy104;
	case '\n':
		yyt2 = yyt4 = yyt5 = yyt8 = yyt9 = yyt10 = yyt14 = current;
		goto yy106;
	case '#':
		yyt2 = yyt3 = current;
		goto yy55;
	case '%':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case '-':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt2 = yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = yyt4 = yyt6 = yyt7 = yyt10 = yyt11 = yyt12 = yyt13 = current;
		goto yy62;
	case ';':
		yyt10 = current;
		goto yy64;
	default:	goto yy63;
	}
yy66:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy75;
	case 'B':
	case 'b':	goto yy78;
	case 'X':
	case 'x':	goto yy79;
	default:	goto yy25;
	}
yy67:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy67;
	case '\n':	goto yy69;
	case '#':
		yyt4 = current;
		goto yy72;
	case '/':
		yyt4 = current;
		goto yy74;
	case ';':	goto yy77;
	default:	goto yy25;
	}
yy69:
	yyaccept = 3;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy67;
	case '\n':	goto yy69;
	case '#':
		yyt4 = current;
		goto yy72;
	case '/':
		yyt4 = current;
		goto yy74;
	case ';':	goto yy77;
	default:	goto yy71;
	}
yy71:
	o1 = yyt1;
	o2 = yyt8;
	o3 = yyt2;
	o4 = yyt3;
#line 113 "src/I386ASM/Parser.re"
	{
                    log << "defin: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << " as "; for (char * cur = o3; cur < o4; cur++) { log << *cur; };log << '\n'; continue;
                  }
#line 1723 "src/I386ASM/Parser.cpp"
yy72:
	++current;
	o1 = yyt1;
	o2 = yyt9;
	o3 = yyt2;
	o4 = yyt3;
	current = yyt4;
#line 116 "src/I386ASM/Parser.re"
	{
                    log << "defin: "; for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << " as "; for (char * cur = o3; cur < o4; cur++) { log << *cur; };log << '\n'; continue;
                  }
#line 1735 "src/I386ASM/Parser.cpp"
yy74:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy72;
	default:	goto yy25;
	}
yy75:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
yy76:
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = current;
		goto yy69;
	case '#':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy74;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy75;
	case ';':
		yyt3 = current;
		goto yy77;
	default:	goto yy25;
	}
yy77:
	++current;
	goto yy71;
yy78:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy108;
	default:	goto yy25;
	}
yy79:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy110;
	default:	goto yy25;
	}
yy80:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy112;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy114;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy80;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy82:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy83:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy84:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy85:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy86:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy117;
	case 'B':
	case 'b':	goto yy118;
	case 'D':
	case 'd':	goto yy119;
	case 'I':
	case 'i':	goto yy87;
	case 'S':
	case 's':	goto yy120;
	default:	goto yy25;
	}
yy87:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy116;
	default:	goto yy25;
	}
yy88:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy116;
	default:	goto yy25;
	}
yy89:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy121;
	case 'B':
	case 'b':	goto yy122;
	case 'C':
	case 'c':	goto yy123;
	case 'D':
	case 'd':	goto yy124;
	case 'E':
	case 'e':	goto yy125;
	case 'I':
	case 'i':	goto yy126;
	case 'S':
	case 's':	goto yy127;
	default:	goto yy25;
	}
yy90:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy128;
	case 'B':
	case 'b':	goto yy130;
	case 'X':
	case 'x':	goto yy131;
	default:	goto yy25;
	}
yy91:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy112;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy114;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy91;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy93:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy93;
	case '\n':	goto yy95;
	case '#':
		yyt3 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ':':	goto yy28;
	case ';':	goto yy103;
	default:	goto yy25;
	}
yy95:
	yyaccept = 4;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy93;
	case '\n':	goto yy95;
	case '#':
		yyt3 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ':':	goto yy28;
	case ';':	goto yy103;
	default:	goto yy97;
	}
yy97:
	o1 = yyt1;
	o2 = yyt10;
	o3 = yyt11;
	o4 = yyt2;
#line 129 "src/I386ASM/Parser.re"
	{
                    log << "inst1: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 2115 "src/I386ASM/Parser.cpp"
yy98:
	++current;
	o1 = yyt1;
	o2 = yyt4;
	o3 = yyt12;
	o4 = yyt5;
	current = yyt3;
#line 135 "src/I386ASM/Parser.re"
	{
                    log << "inst1: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 2130 "src/I386ASM/Parser.cpp"
yy100:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy100;
	case '%':
		yyt4 = current;
		goto yy132;
	case '(':
		yyt4 = current;
		goto yy133;
	case '-':
		yyt4 = current;
		goto yy135;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt4 = current;
		goto yy136;
	default:	goto yy25;
	}
yy102:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy98;
	default:	goto yy25;
	}
yy103:
	++current;
	goto yy97;
yy104:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy104;
	case '\n':	goto yy106;
	case '#':
		yyt3 = current;
		goto yy55;
	case '%':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case ',':	goto yy100;
	case '-':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy80;
	case ':':	goto yy28;
	case ';':	goto yy64;
	default:	goto yy25;
	}
yy106:
	yyaccept = 2;
	marker = ++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy104;
	case '\n':	goto yy106;
	case '#':
		yyt3 = current;
		goto yy55;
	case '%':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy57;
	case '(':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy58;
	case ',':	goto yy100;
	case '-':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy60;
	case '/':
		yyt3 = current;
		goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt3 = yyt2;
		yyt6 = yyt2;
		yyt7 = yyt2;
		yyt11 = yyt12 = yyt13 = current;
		goto yy80;
	case ':':	goto yy28;
	case ';':	goto yy64;
	default:	goto yy54;
	}
yy108:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = current;
		goto yy69;
	case '#':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy74;
	case '0':
	case '1':	goto yy108;
	case ';':
		yyt3 = current;
		goto yy77;
	default:	goto yy25;
	}
yy110:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt3 = current;
		goto yy67;
	case '\n':
		yyt3 = current;
		goto yy69;
	case '#':
		yyt3 = yyt4 = current;
		goto yy72;
	case '/':
		yyt3 = yyt4 = current;
		goto yy74;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy110;
	case ';':
		yyt3 = current;
		goto yy77;
	default:	goto yy25;
	}
yy112:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy112;
	case '\n':	goto yy114;
	case '#':
		yyt3 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ';':	goto yy103;
	default:	goto yy25;
	}
yy114:
	yyaccept = 4;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy112;
	case '\n':	goto yy114;
	case '#':
		yyt3 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ';':	goto yy103;
	default:	goto yy97;
	}
yy116:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt8 = yyt14 = current;
		goto yy138;
	case '\n':
		yyt5 = yyt8 = yyt14 = current;
		goto yy140;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy117:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy118:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy119:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy116;
	default:	goto yy25;
	}
yy120:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt8 = yyt14 = current;
		goto yy138;
	case '\n':
		yyt5 = yyt8 = yyt14 = current;
		goto yy140;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case ';':
		yyt2 = current;
		goto yy103;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy116;
	default:	goto yy25;
	}
yy121:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy122:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy123:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy124:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy125:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy144;
	case 'B':
	case 'b':	goto yy145;
	case 'D':
	case 'd':	goto yy146;
	case 'I':
	case 'i':	goto yy126;
	case 'S':
	case 's':	goto yy147;
	default:	goto yy25;
	}
yy126:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy142;
	default:	goto yy25;
	}
yy127:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy142;
	default:	goto yy25;
	}
yy128:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy112;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy114;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy128;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy130:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy148;
	default:	goto yy25;
	}
yy131:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy150;
	default:	goto yy25;
	}
yy132:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy152;
	case 'B':
	case 'b':	goto yy153;
	case 'C':
	case 'c':	goto yy154;
	case 'D':
	case 'd':	goto yy155;
	case 'E':
	case 'e':	goto yy156;
	case 'I':
	case 'i':	goto yy157;
	case 'S':
	case 's':	goto yy158;
	default:	goto yy25;
	}
yy133:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy133;
	case '%':	goto yy159;
	default:	goto yy25;
	}
yy135:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy160;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy161;
	default:	goto yy25;
	}
yy136:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt9 = yyt12 = current;
		goto yy163;
	case '\n':
		yyt5 = yyt9 = yyt12 = current;
		goto yy165;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy136;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy138:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy138;
	case '\n':	goto yy140;
	case '#':
		yyt3 = current;
		goto yy98;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ';':
		yyt2 = yyt14;
		goto yy103;
	default:	goto yy25;
	}
yy140:
	yyaccept = 5;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy138;
	case '\n':	goto yy140;
	case '#':
		yyt3 = current;
		goto yy98;
	case ',':	goto yy100;
	case '/':
		yyt3 = current;
		goto yy102;
	case ';':
		yyt2 = yyt14;
		goto yy103;
	default:
		yyt2 = yyt14;
		goto yy97;
	}
yy142:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy143:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy142;
	case ')':	goto yy116;
	case ',':	goto yy174;
	default:	goto yy25;
	}
yy144:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy145:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy146:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy142;
	default:	goto yy25;
	}
yy147:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy142;
	default:	goto yy143;
	}
yy148:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy112;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy114;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':	goto yy148;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy150:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy112;
	case '\n':
		yyt2 = yyt5 = yyt8 = yyt14 = current;
		goto yy114;
	case '#':
		yyt3 = yyt5 = current;
		goto yy98;
	case '(':	goto yy58;
	case ',':
		yyt8 = yyt14 = current;
		goto yy100;
	case '/':
		yyt3 = yyt5 = current;
		goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy150;
	case ';':
		yyt2 = current;
		goto yy103;
	default:	goto yy25;
	}
yy152:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy153:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy154:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy155:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy156:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy177;
	case 'B':
	case 'b':	goto yy178;
	case 'D':
	case 'd':	goto yy179;
	case 'I':
	case 'i':	goto yy157;
	case 'S':
	case 's':	goto yy180;
	default:	goto yy25;
	}
yy157:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy176;
	default:	goto yy25;
	}
yy158:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy176;
	default:	goto yy25;
	}
yy159:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy181;
	case 'B':
	case 'b':	goto yy182;
	case 'C':
	case 'c':	goto yy183;
	case 'D':
	case 'd':	goto yy184;
	case 'E':
	case 'e':	goto yy185;
	case 'I':
	case 'i':	goto yy186;
	case 'S':
	case 's':	goto yy187;
	default:	goto yy25;
	}
yy160:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy188;
	case 'B':
	case 'b':	goto yy190;
	case 'X':
	case 'x':	goto yy191;
	default:	goto yy25;
	}
yy161:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt9 = yyt12 = current;
		goto yy163;
	case '\n':
		yyt5 = yyt9 = yyt12 = current;
		goto yy165;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy161;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy163:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy163;
	case '\n':	goto yy165;
	case '#':
		yyt7 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':	goto yy170;
	case '/':
		yyt7 = current;
		goto yy172;
	case ';':	goto yy173;
	default:	goto yy25;
	}
yy165:
	yyaccept = 6;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy163;
	case '\n':	goto yy165;
	case '#':
		yyt7 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':	goto yy170;
	case '/':
		yyt7 = current;
		goto yy172;
	case ';':	goto yy173;
	default:	goto yy167;
	}
yy167:
	o1 = yyt1;
	o2 = yyt3;
	o3 = yyt11;
	o4 = yyt14;
	o5 = yyt4;
	o6 = yyt5;
#line 141 "src/I386ASM/Parser.re"
	{
                    log << "inst2: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 3295 "src/I386ASM/Parser.cpp"
yy168:
	++current;
	o1 = yyt1;
	o2 = yyt6;
	o3 = yyt13;
	o4 = yyt8;
	o5 = yyt4;
	o6 = yyt9;
	current = yyt7;
#line 148 "src/I386ASM/Parser.re"
	{
                    log << "inst2: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 3313 "src/I386ASM/Parser.cpp"
yy170:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy170;
	case '%':
		yyt6 = current;
		goto yy192;
	case '(':
		yyt6 = current;
		goto yy193;
	case '-':
		yyt6 = current;
		goto yy195;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
		yyt6 = current;
		goto yy196;
	default:	goto yy25;
	}
yy172:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy168;
	default:	goto yy25;
	}
yy173:
	++current;
	goto yy167;
yy174:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy174;
	case '%':	goto yy198;
	default:	goto yy25;
	}
yy176:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt9 = yyt12 = current;
		goto yy199;
	case '\n':
		yyt9 = yyt12 = current;
		goto yy201;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy177:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy178:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy179:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy176;
	default:	goto yy25;
	}
yy180:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt9 = yyt12 = current;
		goto yy199;
	case '\n':
		yyt9 = yyt12 = current;
		goto yy201;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case ';':
		yyt5 = current;
		goto yy173;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy176;
	default:	goto yy25;
	}
yy181:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy182:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy183:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy184:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy185:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy205;
	case 'B':
	case 'b':	goto yy206;
	case 'D':
	case 'd':	goto yy207;
	case 'I':
	case 'i':	goto yy186;
	case 'S':
	case 's':	goto yy208;
	default:	goto yy25;
	}
yy186:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy203;
	default:	goto yy25;
	}
yy187:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy203;
	default:	goto yy25;
	}
yy188:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt9 = yyt12 = current;
		goto yy163;
	case '\n':
		yyt5 = yyt9 = yyt12 = current;
		goto yy165;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy188;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy190:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy209;
	default:	goto yy25;
	}
yy191:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy25;
	}
yy192:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy213;
	case 'B':
	case 'b':	goto yy214;
	case 'C':
	case 'c':	goto yy215;
	case 'D':
	case 'd':	goto yy216;
	case 'E':
	case 'e':	goto yy217;
	case 'I':
	case 'i':	goto yy218;
	case 'S':
	case 's':	goto yy219;
	default:	goto yy25;
	}
yy193:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy193;
	case '%':	goto yy220;
	default:	goto yy25;
	}
yy195:
	yych = *++current;
	switch (yych) {
	case '0':	goto yy221;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy222;
	default:	goto yy25;
	}
yy196:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt8 = yyt13 = current;
		goto yy224;
	case '\n':
		yyt8 = yyt13 = current;
		goto yy226;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy196;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy198:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy233;
	case 'B':
	case 'b':	goto yy234;
	case 'C':
	case 'c':	goto yy235;
	case 'D':
	case 'd':	goto yy236;
	case 'E':
	case 'e':	goto yy237;
	case 'I':
	case 'i':	goto yy238;
	case 'S':
	case 's':	goto yy239;
	default:	goto yy25;
	}
yy199:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy199;
	case '\n':	goto yy201;
	case '#':
		yyt7 = current;
		goto yy168;
	case ',':	goto yy170;
	case '/':
		yyt7 = current;
		goto yy172;
	case ';':
		yyt5 = yyt12;
		goto yy173;
	default:	goto yy25;
	}
yy201:
	yyaccept = 7;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy199;
	case '\n':	goto yy201;
	case '#':
		yyt7 = current;
		goto yy168;
	case ',':	goto yy170;
	case '/':
		yyt7 = current;
		goto yy172;
	case ';':
		yyt5 = yyt12;
		goto yy173;
	default:
		yyt5 = yyt12;
		goto yy167;
	}
yy203:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy204:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy203;
	case ')':	goto yy176;
	case ',':	goto yy240;
	default:	goto yy25;
	}
yy205:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy206:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy207:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy203;
	default:	goto yy25;
	}
yy208:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy203;
	default:	goto yy204;
	}
yy209:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt9 = yyt12 = current;
		goto yy163;
	case '\n':
		yyt5 = yyt9 = yyt12 = current;
		goto yy165;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case '0':
	case '1':	goto yy209;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy211:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt5 = yyt9 = yyt12 = current;
		goto yy163;
	case '\n':
		yyt5 = yyt9 = yyt12 = current;
		goto yy165;
	case '#':
		yyt7 = yyt9 = current;
		goto yy168;
	case '(':	goto yy133;
	case ',':
		yyt12 = current;
		goto yy170;
	case '/':
		yyt7 = yyt9 = current;
		goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	case ';':
		yyt5 = current;
		goto yy173;
	default:	goto yy25;
	}
yy213:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy214:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy215:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy216:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy217:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy243;
	case 'B':
	case 'b':	goto yy244;
	case 'D':
	case 'd':	goto yy245;
	case 'I':
	case 'i':	goto yy218;
	case 'S':
	case 's':	goto yy246;
	default:	goto yy25;
	}
yy218:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy242;
	default:	goto yy25;
	}
yy219:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy242;
	default:	goto yy25;
	}
yy220:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy247;
	case 'B':
	case 'b':	goto yy248;
	case 'C':
	case 'c':	goto yy249;
	case 'D':
	case 'd':	goto yy250;
	case 'E':
	case 'e':	goto yy251;
	case 'I':
	case 'i':	goto yy252;
	case 'S':
	case 's':	goto yy253;
	default:	goto yy25;
	}
yy221:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy254;
	case 'B':
	case 'b':	goto yy256;
	case 'X':
	case 'x':	goto yy257;
	default:	goto yy25;
	}
yy222:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt8 = yyt13 = current;
		goto yy224;
	case '\n':
		yyt8 = yyt13 = current;
		goto yy226;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy222;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy224:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy224;
	case '\n':	goto yy226;
	case '#':
		yyt9 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = current;
		goto yy231;
	case ';':	goto yy232;
	default:	goto yy25;
	}
yy226:
	yyaccept = 8;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy224;
	case '\n':	goto yy226;
	case '#':
		yyt9 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = current;
		goto yy231;
	case ';':	goto yy232;
	default:	goto yy228;
	}
yy228:
	o1 = yyt1;
	o2 = yyt7;
	o3 = yyt11;
	o4 = yyt14;
	o5 = yyt4;
	o6 = yyt12;
	o7 = yyt6;
	o8 = yyt8;
#line 155 "src/I386ASM/Parser.re"
	{
                    log << "inst3: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o7; cur < o8; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 4183 "src/I386ASM/Parser.cpp"
yy229:
	++current;
	o1 = yyt1;
	o2 = yyt3;
	o3 = yyt11;
	o4 = yyt14;
	o5 = yyt4;
	o6 = yyt12;
	o7 = yyt6;
	o8 = yyt13;
	current = yyt9;
#line 163 "src/I386ASM/Parser.re"
	{
                    log << "inst3: ";
                    for (char * cur = o1; cur < o2; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o3; cur < o4; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o5; cur < o6; cur++) { log << *cur; }; log << ' ';
                    for (char * cur = o7; cur < o8; cur++) { log << *cur; }; log << ' ';
                    log << '\n'; continue;
                  }
#line 4204 "src/I386ASM/Parser.cpp"
yy231:
	yych = *++current;
	switch (yych) {
	case '*':
	case '/':	goto yy229;
	default:	goto yy25;
	}
yy232:
	++current;
	goto yy228;
yy233:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy234:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy235:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy236:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy237:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy260;
	case 'B':
	case 'b':	goto yy261;
	case 'D':
	case 'd':	goto yy262;
	case 'I':
	case 'i':	goto yy238;
	case 'S':
	case 's':	goto yy263;
	default:	goto yy25;
	}
yy238:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy258;
	default:	goto yy25;
	}
yy239:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy258;
	default:	goto yy25;
	}
yy240:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy240;
	case '%':	goto yy264;
	default:	goto yy25;
	}
yy242:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt13 = current;
		goto yy265;
	case '\n':
		yyt13 = current;
		goto yy267;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy243:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy244:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy245:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy242;
	default:	goto yy25;
	}
yy246:
	yych = *++current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt13 = current;
		goto yy265;
	case '\n':
		yyt13 = current;
		goto yy267;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case ';':
		yyt8 = current;
		goto yy232;
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy242;
	default:	goto yy25;
	}
yy247:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy248:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy249:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy250:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy251:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy271;
	case 'B':
	case 'b':	goto yy272;
	case 'D':
	case 'd':	goto yy273;
	case 'I':
	case 'i':	goto yy252;
	case 'S':
	case 's':	goto yy274;
	default:	goto yy25;
	}
yy252:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy269;
	default:	goto yy25;
	}
yy253:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy269;
	default:	goto yy25;
	}
yy254:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt8 = yyt13 = current;
		goto yy224;
	case '\n':
		yyt8 = yyt13 = current;
		goto yy226;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy254;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy256:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':	goto yy275;
	default:	goto yy25;
	}
yy257:
	yych = *++current;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy277;
	default:	goto yy25;
	}
yy258:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy259:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy258;
	case ')':	goto yy116;
	case ',':	goto yy279;
	default:	goto yy25;
	}
yy260:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy261:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy262:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy258;
	default:	goto yy25;
	}
yy263:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy258;
	default:	goto yy259;
	}
yy264:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy281;
	case 'B':
	case 'b':	goto yy282;
	case 'C':
	case 'c':	goto yy283;
	case 'D':
	case 'd':	goto yy284;
	case 'E':
	case 'e':	goto yy285;
	case 'I':
	case 'i':	goto yy286;
	case 'S':
	case 's':	goto yy287;
	default:	goto yy25;
	}
yy265:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy265;
	case '\n':	goto yy267;
	case '#':
		yyt9 = current;
		goto yy229;
	case '/':
		yyt9 = current;
		goto yy231;
	case ';':
		yyt8 = yyt13;
		goto yy232;
	default:	goto yy25;
	}
yy267:
	yyaccept = 9;
	marker = ++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':	goto yy265;
	case '\n':	goto yy267;
	case '#':
		yyt9 = current;
		goto yy229;
	case '/':
		yyt9 = current;
		goto yy231;
	case ';':
		yyt8 = yyt13;
		goto yy232;
	default:
		yyt8 = yyt13;
		goto yy228;
	}
yy269:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy270:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy269;
	case ')':	goto yy242;
	case ',':	goto yy288;
	default:	goto yy25;
	}
yy271:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy272:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy273:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy269;
	default:	goto yy25;
	}
yy274:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy269;
	default:	goto yy270;
	}
yy275:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt8 = yyt13 = current;
		goto yy224;
	case '\n':
		yyt8 = yyt13 = current;
		goto yy226;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case '0':
	case '1':	goto yy275;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy277:
	++current;
	if ((limit - current) < 2) if (!fillBuffer(2, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case ' ':
		yyt8 = yyt13 = current;
		goto yy224;
	case '\n':
		yyt8 = yyt13 = current;
		goto yy226;
	case '#':
		yyt9 = yyt13 = current;
		goto yy229;
	case '(':	goto yy193;
	case '/':
		yyt9 = yyt13 = current;
		goto yy231;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy277;
	case ';':
		yyt8 = current;
		goto yy232;
	default:	goto yy25;
	}
yy279:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy279;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy290;
	default:	goto yy25;
	}
yy281:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy282:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy283:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy284:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy285:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy294;
	case 'B':
	case 'b':	goto yy295;
	case 'D':
	case 'd':	goto yy296;
	case 'I':
	case 'i':	goto yy286;
	case 'S':
	case 's':	goto yy297;
	default:	goto yy25;
	}
yy286:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy292;
	default:	goto yy25;
	}
yy287:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy292;
	default:	goto yy25;
	}
yy288:
	++current;
	if ((limit - current) < 6) if (!fillBuffer(6, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy288;
	case '%':	goto yy298;
	default:	goto yy25;
	}
yy290:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy290;
	case ')':	goto yy116;
	default:	goto yy25;
	}
yy292:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy293:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy292;
	case ')':	goto yy176;
	case ',':	goto yy299;
	default:	goto yy25;
	}
yy294:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy295:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy296:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy292;
	default:	goto yy25;
	}
yy297:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy292;
	default:	goto yy293;
	}
yy298:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'a':	goto yy301;
	case 'B':
	case 'b':	goto yy302;
	case 'C':
	case 'c':	goto yy303;
	case 'D':
	case 'd':	goto yy304;
	case 'E':
	case 'e':	goto yy305;
	case 'I':
	case 'i':	goto yy306;
	case 'S':
	case 's':	goto yy307;
	default:	goto yy25;
	}
yy299:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy299;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy308;
	default:	goto yy25;
	}
yy301:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'X':
	case 'h':
	case 'l':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy302:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'P':
	case 'X':
	case 'h':
	case 'l':
	case 'p':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy303:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'l':
	case 's':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy304:
	yych = *++current;
	switch (yych) {
	case 'H':
	case 'I':
	case 'L':
	case 'S':
	case 'X':
	case 'h':
	case 'i':
	case 'l':
	case 's':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy305:
	yych = *++current;
	switch (yych) {
	case 'A':
	case 'C':
	case 'a':
	case 'c':	goto yy312;
	case 'B':
	case 'b':	goto yy313;
	case 'D':
	case 'd':	goto yy314;
	case 'I':
	case 'i':	goto yy306;
	case 'S':
	case 's':	goto yy315;
	default:	goto yy25;
	}
yy306:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'p':	goto yy310;
	default:	goto yy25;
	}
yy307:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'S':
	case 'i':
	case 'p':
	case 's':	goto yy310;
	default:	goto yy25;
	}
yy308:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy308;
	case ')':	goto yy176;
	default:	goto yy25;
	}
yy310:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
yy311:
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy310;
	case ')':	goto yy242;
	case ',':	goto yy316;
	default:	goto yy25;
	}
yy312:
	yych = *++current;
	switch (yych) {
	case 'X':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy313:
	yych = *++current;
	switch (yych) {
	case 'P':
	case 'X':
	case 'p':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy314:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'X':
	case 'i':
	case 'x':	goto yy310;
	default:	goto yy25;
	}
yy315:
	yych = *++current;
	switch (yych) {
	case 'I':
	case 'P':
	case 'i':
	case 'p':	goto yy310;
	default:	goto yy311;
	}
yy316:
	++current;
	if (limit <= current) if (!fillBuffer(1, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy316;
	case ',':
	case '1':
	case '2':
	case '4':
	case '8':	goto yy318;
	default:	goto yy25;
	}
yy318:
	++current;
	if ((limit - current) < 3) if (!fillBuffer(3, input)) break;
	yych = *current;
	switch (yych) {
	case '\t':
	case '\n':
	case ' ':	goto yy318;
	case ')':	goto yy242;
	default:	goto yy25;
	}
}
#line 172 "src/I386ASM/Parser.re"

    }
    
    log << "parse input done\n";
    return list;
}
